name: Step 3, Merge your pull request

# This step triggers after pushing to main
# This step sets STEP to 4
# This step closes <details id=3> and opens <details id=4> <id=5> and <id=X>

# This will run every time we push to main
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_TBD:
    name: On TBD

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 3 (see update-step.sh)
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ github.repository_owner != 'githublearn' }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      # TBD include any further steps here

      # TBD custom step finish here, close 3, open 4, 5, and X; set STEP to X
